# Generated by Django 5.2 on 2025-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
