# Generated by Django 5.2 on 2025-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_remove_news_image_news_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="news",
            name="summary",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
