# Generated by Django 5.2 on 2025-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_remove_news_image_url_remove_news_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
